version: '3'

services:
  milvus-mcp:
    build: .
    ports:
      - "8085:8085"
    environment:
      - MILVUS_URI=http://milvus:19530
      - MILVUS_TOKEN=
      - MILVUS_DB=default
    depends_on:
      - milvus
    restart: always

  milvus:
    image: milvusdb/milvus:latest
    ports:
      - "19530:19530"
      - "9091:9091"
    volumes:
      - ./milvus/data:/var/lib/milvus/data
      - ./milvus/conf:/var/lib/milvus/conf
      - ./milvus/logs:/var/lib/milvus/logs
    environment:
      - ETCD_ENDPOINTS=etcd:2379
      - MINIO_ADDRESS=minio:9000
    restart: always

  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ./etcd/data:/etcd
    command: etcd --advertise-client-urls=http://0.0.0.0:2379 --listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    restart: always

  minio:
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    volumes:
      - ./minio/data:/data
    command: minio server /data
    restart: always